POST http://localhost:4004/api/wms/UploadASN
Content-Type: application/json

{
	"receiptkey": "0000003344",
	"storerkey": "1031846",
	"serialkey": 3344,
	"externreceiptkey": "WMS0000003344",
	"editdate": "2026-03-18T16:21:29.000Z",
	"adddate": "2026-03-18T16:21:29.000Z",
	"notes": null,
	"referencetype": "PurchaseOrder",
	"referencedocument": "4500650537",
	"referenceaccountingentity": "1031846",
	"referencelocation": null,
	"actualshipdate": null,
	"expectedreceiptdate": "2026-03-16T00:00:00.000Z",
	"grossweight": "0.00000",
	"totalvolume": "0.00000",
	"transportationmode": null,
	"supplierkey": null,
	"suppliername": null,
	"shipfromaddressline1": null,
	"shipfromaddressline2": null,
	"shipfromaddressline3": null,
	"shipfromaddressline4": null,
	"shipfromaddressline5": null,
	"shipfromaddressline6": null,
	"shipfromcity": null,
	"shipfromstate": null,
	"shipfromisocountry": null,
	"shipfromzip": null,
	"shipfromcontact": null,
	"shipfromphone": null,
	"shipfromemail": null,
	"carrierkey": null,
	"carriername": null,
	"carrieraddress1": null,
	"carrieraddress2": null,
	"carriercity": null,
	"carrierstate": null,
	"carriercountry": null,
	"carrierzip": null,
	"carrierphone": null,
	"returnfromparty": null,
	"accountingentity": null,
	"company": "Ransa Comercial - CD Perecederos",
	"address1": "Av. Argentina 2833",
	"address2": null,
	"address3": null,
	"address4": "CALLAO",
	"city": "PROV. CONST. CALLAO",
	"state": "CALLAO",
	"isocntrycode": "Peru",
	"zip": "070101",
	"phone1": null,
	"freightcostamount": "0.00000",
	"tmfreightcostcurrency": null,
	"freightcostbaseamount": "0.00000",
	"freightchargeamount": null,
	"tmfreightchargecurrency": null,
	"freightchargebaseamount": "0.00000",
	"requireddeliverydate": null,
	"promiseddeliverydate": null,
	"earliestshipdate": null,
	"promisedshipdate": null,
	"scheduledshipdate": null,
	"transportationservice": null,
	"incoterms": null,
	"pronumber": null,
	"earliestdeliverydate": null,
	"verifiedcloseddate": "2026-03-18T16:21:29.000Z",
	"type": "7",
	"cantidad_lpns_recibidos": "1.00000",
	"codigo_de_propietario": "1031846",
	"nombre_de_propietario": "Bembos",
	"id_usuario": "cmorang@ransa.net",
	"estado_de_recepcion": "Verificado Cerrado",
	"transactionid": null,
	"whseid": "WHSE20",
	"susr3": null,
	"ext_udf_lkup1": null,
	"details": [
		{
			"sku": "200923",
			"storerkey": "1031846",
			"descr": "LECHUGA PICADA (UN X 1 KG)",
			"notes": null,
			"qtyexpected": "1.00000",
			"packuom3": "KG",
			"requisitiondocument": null,
			"requisitionaccountingentity": null,
			"requisitionlocation": null,
			"requisitionline": null,
			"purchaseorderdocument": "4500650537",
			"purchaseorderaccountingentity": "1031846",
			"purchaseorderlocation": null,
			"purchaseorderline": "00010",
			"purchaseorderscheduleline": null,
			"salesorderdocument": null,
			"salesorderaccountingentity": null,
			"salesorderlocation": null,
			"salesorderline": null,
			"salesorderscheduleline": null,
			"referencetype": "PurchaseOrder",
			"referencedocument": "4500650537",
			"referenceaccountingentity": "1031846",
			"referenceline": "00010",
			"referencescheduleline": null,
			"extendedprice": "0.00000",
			"sublinenumber": null,
			"lottable09": "180327",
			"lottable10": null,
			"externlineno": "WMS00001",
			"codigo_propietario": "1031846",
			"codigo_almacen": "WHSE20",
			"qtyreceived": "1.00000",
			"cantidad_en_cajas": "1.00000",
			"cube": "1.00000",
			"grosswgt": "1.00000",
			"netwgt": "1.00000",
			"uom": "UN",
			"externpokey": "4500650537",
			"externpolineno": "00010",
			"lottable01": null,
			"lottable02": "1031846",
			"lottable03": "00030",
			"fecha_de_produccion": null,
			"fecha_de_vencimiento": "2027-03-18T00:00:00.000Z",
			"lottable06": "2026-03-18",
			"lottable07": null,
			"lottable08": null,
			"lottable11": null,
			"lottable12": null,
			"toid": "LPN260318004",
			"tolot": "0000009764",
			"matchlottable": "0",
			"Tarewgt": "0.00000",
			"Fillqtyuom": "UN"
		}
	]
}


########################
########################

POST http://localhost:4004/api/wms/UploadOrdenExpedicion
Content-Type: application/json

{
	"orderkey": "0000036653",
	"orders_storerkey": "AE1",
	"storer_storerkey": "WHSE21",
	"serialkey": 96454,
	"externorderkey": "C7523379",
	"editwho": "lsachuns",
	"orderdate": "2025-10-21T12:00:00.000Z",
	"referencetype": "1",
	"referencedocument": "0000420685",
	"referenceaccountingentity": null,
	"referencelocation": "TRU-05968-102025-VALMIS 1511_2",
	"accountingentity": null,
	"storer_company": "Ransa Comercial - Trujillo Bravo",
	"address1": "Prologación Gonzales Prada",
	"address2": "Ex Fundo Larrea",
	"address3": "TRUJILLO",
	"address4": null,
	"state": "TRUJILLO",
	"zip": "130101",
	"externalloadid": null,
	"carrierrouteaccountingentity": null,
	"carrierroutelocation": null,
	"route": "DV",
	"actualshipdate": "2025-11-14T14:45:59.000Z",
	"scheduleddelvdate": null,
	"actualdelvdate": null,
	"hazmatcodeskey": null,
	"transportationmode": null,
	"door": "YARD",
	"city": "LA LIBERTAD",
	"isocntrycode": "PE",
	"phone1": null,
	"carriercode": null,
	"accounting": null,
	"carriername": null,
	"carrieraddress1": null,
	"carrieraddress2": null,
	"carriercity": null,
	"carrierstate": null,
	"carrierisocntrycode": null,
	"carrierzip": null,
	"carrierphone": null,
	"pmtterm": null,
	"returntoparty": null,
	"c_company": "VALE MISKI MAYO FOALI",
	"c_address1": "MINERA BAYOVAR CARRETERA SECHURA  KM 36.5",
	"c_address2": "SECHURA",
	"c_address3": null,
	"c_address4": "SN",
	"c_address5": null,
	"c_address6": "SECHURA",
	"c_city": "SECHURA",
	"c_state": "PIURA",
	"c_isocntrycode": "PE",
	"c_zip": null,
	"c_phone1": null,
	"consigneekey": "C005670",
	"c_vat": null,
	"ordervalue": null,
	"freightcostamount": null,
	"tmfreightcostcurrency": null,
	"freightchargeamount": null,
	"tmfreightchargecurrency": null,
	"deliverydate": "2025-10-21T12:00:00.000Z",
	"promiseddelvdate": null,
	"earliestshipdate": null,
	"promisedshipdate": null,
	"scheduledshipdate": null,
	"requestedshipdate": null,
	"plannedshipdate": null,
	"planneddelvdate": null,
	"shiptogether": "true",
	"priority": "1",
	"orders_transportationservice": null,
	"countrydestination": null,
	"stage": null,
	"incoterm": null,
	"pronumber": null,
	"tmhouseairwaybillnumber": null,
	"tmmasterairwaybill": null,
	"tmbookingnumber": null,
	"tmhouseoceanbol": null,
	"tmmasteroceanbolnumber": null,
	"tmequipmentnumber": null,
	"tmsealnumber": null,
	"tmlicenseplatenumber": null,
	"trailerid": "T9O852/AAJ976",
	"earliestdeliverydate": null,
	"tmserviceattribute": null,
	"orderdetail_transportationserv": null,
	"defaulttransportationservice": null,
	"tmequipmenttype": null,
	"tmequipmentlength": null,
	"tmportofloading": null,
	"tmportofdischarge": null,
	"tmoceanservicelevel": null,
	"tmroutedvia": null,
	"tmairservicelevel": null,
	"tmequipmentattribute": null,
	"parent": "20414766308",
	"splitshipmentindicator": null,
	"splitshipmentfinalshipment": null,
	"orders_storer": "21317",
	"nombre_de_almacen": "Ransa Comercial - Trujillo Bravo",
	"loadid": "0000420685",
	"company": "SODEXO PERU SAC",
	"informacion_del_conductor": null,
	"orders_conductor": null,
	"ext_udf_lkup1": null,
	"susr1": null,
	"susr2": null,
	"susr3": null,
	"susr4": null,
	"susr5": null,
	"billtokey": null,
	"b_address1": null,
	"b_address2": null,
	"b_address3": null,
	"b_address4": null,
	"b_address5": null,
	"b_address6": null,
	"b_city": null,
	"b_company": null,
	"b_contact1": null,
	"b_isocntrycode": null,
	"b_state": null,
	"splitshipmentoriginalorderkey": null,
	"referencenum": null,
	"ruc_shipto": null,
	"ruc_billto": null,
	"notes": null,
	"type": "1",
	"transactionid": null,
	"details": [
		{
			"orderkey": "0000036653",
			"storer_storerkey": "WHSE21",
			"sku": "C0402080001.24",
			"accountingentity": null,
			"descr": "JUGO DE DURAZNO FRUGOS 235 ML",
			"notes": null,
			"hazmatcodekey": null,
			"containerdetailid": null,
			"fulfillqty": "240.00000",
			"packuom3": "CAJ",
			"qty": "240.00000",
			"purchaseorderdocument": null,
			"purchaseorderaccountingentity": null,
			"purchaseorderlocation": null,
			"purchaseorderline": null,
			"purchaseorderscheduleline": null,
			"salesorderdocument": null,
			"referencetype": null,
			"referencedocument": null,
			"referenceaccountingentity": null,
			"referencelocation": null,
			"referenceline": null,
			"referencescheduleline": null,
			"unitprice": "0.00000",
			"freightclass": null,
			"externallocsequence": "2",
			"oother2": "NA",
			"lottable09": "NA",
			"oother1": "NA",
			"lottable10": null,
			"wgt": null,
			"externlineno": "2",
			"holdcode": "",
			"componentqty": null,
			"minshippercent": 0,
			"oqcrequired": "0",
			"oqcautoadjust": "0",
			"qtysum": "240.00000",
			"qtyrejected": null,
			"rejectedreason": null,
			"loadid": "0000420685",
			"originalqty": "240.00000",
			"dimenuom": "CM",
			"wgtuom": "KG",
			"product_cube": "13920.00000",
			"product_weight": "72.00000",
			"cantidad_despachada_en_cajas": "10.00000",
			"lottable01": null,
			"lottable02": "21317",
			"lottable03": "0",
			"lottable04": null,
			"lottable05": "2026-04-21T00:00:00.000Z",
			"lottable06": null,
			"lottable07": "006599",
			"lottable08": "AC COMERCIAL DEL PERU S.A.C (TRUJILLO)",
			"pickdetailkey": null,
			"orders_storer": "21317",
			"unitdetails": [
				{
					"pickdetailkey": "0000711645",
					"trackingid": null,
					"dropid": "0000420685",
					"caseid": "TRU-05968-102025-VALMIS 1511_2-1411",
					"freightcharges": "0.00000",
					"width": "0.00000",
					"length": "0.00000",
					"height": "0.00000",
					"containertype": "0.00000",
					"salesorderaccountingentity": null,
					"salesorderlocation": null,
					"salesorderline": null,
					"freightclass": "0.00000",
					"dropidtype": "0",
					"cantidad_despachada_unidades": "240.00000",
					"loadid": "0000420685",
					"packuom3": "CAJ",
					"dimenuom": "CM",
					"wgtuom": "KG",
					"cantidad_despachada_en_cajas": "10.00000",
					"busr1": null,
					"busr2": null,
					"busr3": "JUGO DE DURAZNO FRUGOS 235 ML",
					"busr4": "",
					"busr5": "240.00000",
					"busr6": "0",
					"busr7": "0",
					"idseguimiento": null,
					"detail_lottable09": "NA",
					"net_weight": "72.00000",
					"tare_weight": "0.00000",
					"gross_weight": "72.00000",
					"total_pallet_weight": "0.00000",
					"pickdetail_fecha_vencimiento": null
				}
			]
		},
		{
			"orderkey": "0000036653",
			"storer_storerkey": "WHSE21",
			"sku": "C23010130042.12",
			"accountingentity": null,
			"descr": "SHAMPOO PANTENE 18 ML",
			"notes": null,
			"hazmatcodekey": null,
			"containerdetailid": null,
			"fulfillqty": "24.00000",
			"packuom3": "SCH",
			"qty": "24.00000",
			"purchaseorderdocument": null,
			"purchaseorderaccountingentity": null,
			"purchaseorderlocation": null,
			"purchaseorderline": null,
			"purchaseorderscheduleline": null,
			"salesorderdocument": null,
			"referencetype": null,
			"referencedocument": null,
			"referenceaccountingentity": null,
			"referencelocation": null,
			"referenceline": null,
			"referencescheduleline": null,
			"unitprice": "0.00000",
			"freightclass": null,
			"externallocsequence": "1",
			"oother2": "NA",
			"lottable09": "NA",
			"oother1": "NA",
			"lottable10": null,
			"wgt": null,
			"externlineno": "1",
			"holdcode": "",
			"componentqty": null,
			"minshippercent": 0,
			"oqcrequired": "0",
			"oqcautoadjust": "0",
			"qtysum": "24.00000",
			"qtyrejected": null,
			"rejectedreason": null,
			"loadid": "0000420685",
			"originalqty": "24.00000",
			"dimenuom": null,
			"wgtuom": null,
			"product_cube": "0.00000",
			"product_weight": "1.20000",
			"cantidad_despachada_en_cajas": "2.00000",
			"lottable01": null,
			"lottable02": "21317",
			"lottable03": "0",
			"lottable04": null,
			"lottable05": "2026-11-18T00:00:00.000Z",
			"lottable06": null,
			"lottable07": "005182",
			"lottable08": "TODOPACK SAC",
			"pickdetailkey": null,
			"orders_storer": "21317",
			"unitdetails": [
				{
					"pickdetailkey": "0000711644",
					"trackingid": null,
					"dropid": "0000420685",
					"caseid": "TRU-05968-102025-VALMIS 1511_2-1411",
					"freightcharges": "0.00000",
					"width": "0.00000",
					"length": "0.00000",
					"height": "0.00000",
					"containertype": "0.00000",
					"salesorderaccountingentity": null,
					"salesorderlocation": null,
					"salesorderline": null,
					"freightclass": "0.00000",
					"dropidtype": "0",
					"cantidad_despachada_unidades": "24.00000",
					"loadid": "0000420685",
					"packuom3": "SCH",
					"dimenuom": null,
					"wgtuom": null,
					"cantidad_despachada_en_cajas": "2.00000",
					"busr1": null,
					"busr2": null,
					"busr3": "SHAMPOO PANTENE 18 ML",
					"busr4": "",
					"busr5": "24.00000",
					"busr6": "0",
					"busr7": "0",
					"idseguimiento": null,
					"detail_lottable09": "NA",
					"net_weight": "1.20000",
					"tare_weight": "0.00000",
					"gross_weight": "1.20000",
					"total_pallet_weight": "0.00000",
					"pickdetail_fecha_vencimiento": null
				}
			]
		}
	]
}




########################
########################

POST http://localhost:4004/api/wms/UploadConfirmacionGuia
Content-Type: application/json

{
	"guia": "T008-1",
	"pedidos": ["10232323A","10232323B","10232323C"]
}